# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('riskview_all', 'Can see all the pages'), ('riskview_dev', 'Can see dev page'), ('riskview_transfer', 'Can see transfer page'))},
        ),
    ]
