# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_with_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='other',
        ),
    ]
