# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play_with_auth', '0002_remove_users_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='tenant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='play_with_auth.Tenants'),
        ),
    ]
