# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_with_auth', '0004_auto_20170615_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password_expired',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
