# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_with_signal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='foo',
            name='bar',
        ),
    ]
