# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20160628_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='query',
            name='formated',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='query',
            name='owner',
            field=models.CharField(default='', max_length=30),
        ),
    ]
