# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20160628_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ('-created',)},
        ),
    ]
